### PR TITLE
Ran 2to3

### PR DESCRIPTION
**Pull request by btnpushnmunky**
Ran 2to3 to make dodo compatible with Python 3. Installed and tested (minimally) with 2.7.9 and 3.4.3.

### CODE REVIEW

**Comment by atmb4u** [comment]
Good work @btnpushnmunky. But there are a lot of stray files in the commit which I cannot include to the repository. Could you please create a new branch off the master and another pull request **just with the dodo.py** file.

**Comment by btnpushnmunky** [comment]
Dangit. Yes. I should've watched that. Will do.

**Comment by btnpushnmunky** [comment]
I've removed the clutter in my original python3 branch. Can you merge from that or do you need a separate branch completely?

**Comment by atmb4u** [comment]
I'd recommend if you work on the current master and make changes to the dodo.py there and create a pull request for the same. That would keep the code base clean. Thanks.

**Comment by btnpushnmunky** [comment]
Will do. The setup.py file will need a couple of changes as well.

**Pull request closed without merging**
